# Site settings
username: Bablon
title: The Hanging Gardens
email: your-email@domain.com
description: "bablon's blog"
baseurl: ""
#url: "http://yourdomain.com"

encoding: utf-8

# Build settings
markdown: kramdown
permalink: pretty
