# Site settings
username: Bablon
title: The Hanging Gardens
email: your-email@domain.com
description: "bablon's blog"
baseurl: ""
#url: "http://yourdomain.com"

encoding: UTF-8

# Build settings
markdown: rdiscount
# markdown: kramdown
permalink: pretty
# permalink: /:categories/:year/:month/:day/:title
